##common
server:
  port: 80
  servlet:
    context-path: /
spring:
  profiles:
    active: @spring.profiles.active@
    group:
      dev:
      - "dev"
--- #dev
spring:
  config:
    activate:
      on-profile: dev
  web:    
    resources:
      cache:
        cachecontrol:
          no-cache: true
          max-age: 0
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: inspace123
logging:
  level:
    web: info
    '[com.zaxxer.hikari.HikariConfig]': error
    '[com.zaxxer.hikari]': error
    jdbc:
      jdbc: off
      sqlonly: debug
      sqltiming: off
      audit: off
      resultset: off
      resultsettable: off
      connection: off
mybatis:
  type-aliases-package: com.example.myapp.dto
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
